language: java
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.m2"
before_install:
- export APP_VERSION="`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate
  -Dexpression=project.version | grep -Ev '(^\[|Download\w+:)'`-$TRAVIS_BUILD_NUMBER"
- echo $APP_VERSION
script:
- mvn versions:set -DnewVersion=$APP_VERSION
- mvn clean package
before_deploy:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git commit -a -m "Set version to $APP_VERSION"
- git tag $APP_VERSION -a -m "Generated tag from TravisCI for $APP_VERSION"
- git push -q -f https://$GITHUB_API_KEY@github.com/imduffy15/keycloak-jms-event-forwarder --tags
  --tags
deploy:
  provider: releases
  api_key: $GITHUB_API_KEY
  file: target/jms-event-forwarder-$APP_VERSION.jar
  on:
    repo: imduffy15/keycloak-jms-event-forwarder
    tags: false
    branch: master
env:
  global:
    secure: AYgixwJHj08AUgtWdER9wYWe6lR01yTzz+IM7qXyY3IQPy+Sn/l8EsA1hEcftx6NDQHZK4lBxVoXXmY+d5+Uc6ibsa4kRqOyEKP7F5mRSs2Iol2NncaIBTUW4GHW8HzkGl5ZpeIr0YG3WDhWFiQoJppVds/Cb+uFhR/sn2SiRIm3T89fqXXm6lBNR463lwfoR38V3WWirwobShBuY1pjfSxAw2QzjNl3LM2M6xbUYwS1jA/InAM/Qct7LAePBDnnkcSZmz10uHvoQwL6/lbNNy2wXJYbfQjw8sdNxSgT+z4dIx92sR+14bwwXHCYJ6yRW95eY66Sy9hNaPWpJTwI4R1cVzpWTwPlIacB168R8YpkvgHHts2YnHbS98ypuZPaGwQDSWFiG1v0ecMzIckCSKiOqF0R8IoWlbIUD3zDuWG4kdC/upq0umgOr1WPQEde/CYqX7sAxJQaISHIfqImqAepOCF1Mv/DGcGWI1j2LD/lKeFPCDFAP/OOiIGl5M7N+w0cYjdQWwm0voT4WfsRw4yWiXw5Y3+cgu5yGuemP2PTsfdB9hNHjQtCLnQGCn83f0q61tII0IwRelBeYosg2/axLGDo1SUdT436YP9AgFEp9YsSCvZa07ET/fg2wYSJUsr/t3UocItUp40cc63o1MbmFZXpHdLcd97i9V7ZRdU=
